SR - content component
elektronstudio/elektro pull request #9
Opened 2022-01-07 12:32 UTC by sven-ra

2022-01-07 14:11 UTC, kristjanjansen requested changes

2022-01-07 14:11 UTC, kristjanjansen commented on src/components/EContent.vue
> +  el?: string;
Ma paneks `"article" | "section" | string` n2iteks siis on autocompletes kena vaadata. Lisa veel sobivaid semantic tage kui midagi meelde tuleb.

2022-01-07 14:11 UTC, kristjanjansen commented on src/components/EContent.vue
> +  /* Use closest value or add custom values? */
Pane praegu `styles.css`i uus variable mille nimi on l2him tw skaalale ja v22rtus on 1.375 -- see on siis nagu override. parast vaatab kuidas adjustida tw asju.

2022-01-07 14:11 UTC, kristjanjansen commented on src/components/EContent.vue
> +  font-size: var(--text-xs);
ei tohiks vist body tekstist vaiksem olla. Alternatiiv on yldse mitte h6 suurusega tegeleda, vaga vahekasutet.

2022-01-07 14:11 UTC, kristjanjansen commented on src/components/EContent.vue
> +}
Oleks vaja juurde `EContent a` ja `EContent blockquote`

2022-01-07 14:11 UTC, kristjanjansen commented on src/pages/Components.vue
> +      Aenean eu <i>leo quam.</i> Pellentesque <b>ornare sem</b> lacinia quam
Votaks reaalse teksti eesti ja inglise keelest elektron.art'ist. _Occidere Lorem Ipsum!_

2022-01-08 15:45 UTC, sven-ra commented on src/components/EContent.vue
> +  font-size: var(--text-xs);
Las see praegu olla siis. Asi selles, et meil muidu "small text" ka kujunduses. Ma ei kavatsend selleks h6 kasutada, aga  ei ole vist ju väikseks tekstiks HTML tagi? Ei tule pähe ka WYSIWYG või markdown varianti.

2022-01-10 08:42 UTC, kristjanjansen commented on src/components/EContent.vue
> +  font-size: var(--text-xs);
https://htmlreference.io/element/small :)

2022-01-10 08:47 UTC, kristjanjansen requested changes
Natuke veel j22nud :)

2022-01-10 08:47 UTC, kristjanjansen commented on src/components/EContent.vue
> +// TODO: find proper ElementType typing
Pole TODOd enam vaja

2022-01-10 08:47 UTC, kristjanjansen commented on src/components/EContent.vue
> +  font-size: var(--text-xs);
https://htmlreference.io/element/small :)

2022-01-10 08:47 UTC, kristjanjansen commented on src/components/EContent.vue
> +  background-image: url("/images/bg-texture-xs.gif");
Cool aga akki motleme yle. `clip: text` ei tundu toimivat Chromega
<img width="1280" alt="Screenshot 2022-01-10 at 10 45 25" src="https://user-images.githubusercontent.com/241603/148738680-89086637-7d92-49a7-9ebe-91a0301a4d53.png">
.

2022-01-10 16:17 UTC, merged